/*
 * Copyright (C) 2026 aspectk
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.molelabs.aspectk.runtime.internal

import io.github.molelabs.aspectk.runtime.MethodSignature
import io.github.molelabs.aspectk.runtime.ProceedingJoinPoint

/**
 * Default [ProceedingJoinPoint] implementation generated by the AspectK compiler plugin for
 * [io.github.molelabs.aspectk.runtime.Around]-intercepted functions.
 *
 * This class is an internal implementation detail and should not be referenced directly
 * by user code. Program to the [ProceedingJoinPoint] interface instead.
 *
 * At each intercepted call site the compiler plugin emits code equivalent to:
 * ```kotlin
 * DefaultProceedingJoinPoint(
 *     target    = this,
 *     signature = $MethodSignatures.ajc$tjp_0,
 *     args      = listOf(arg0, arg1, ...),
 *     proceedFn = { __args -> /* original function body with params rebound */ }
 * )
 * ```
 *
 * @property target The receiver of the intercepted function call, or `null` for top-level
 *   or static functions.
 * @property signature The pre-built static [io.github.molelabs.aspectk.runtime.MethodSignature]
 *   associated with the intercepted function.
 * @property args The runtime arguments passed to the intercepted function, in declaration order.
 * @property proceedFn The lambda that executes the original function body.
 *   Receives the argument list to use when invoking the body.
 */
public class DefaultProceedingJoinPoint(
    override val target: Any?,
    override val signature: MethodSignature,
    override val args: List<Any?>,
    private val onProceedListener: ProceedingJoinPoint.OnProceedListener,
) : ProceedingJoinPoint {
    override fun proceed(): Any? = onProceedListener.onProceed(args)

    override fun proceed(vararg args: Any?): Any? {
        // `args` contains only the regular (non-receiver) parameters supplied by the caller.
        // The wrapper lambda expects the full list in the same order as `this.args`:
        // [receiver?, param0, param1, ...]. So we copy the original list and overwrite
        // only the trailing regular-parameter slots.
        val fullArgs = this.args.toMutableList()
        val offset = fullArgs.size - args.size
        require(offset >= 0) {
            "proceed(vararg) received ${args.size} args but the function has ${fullArgs.size} total"
        }
        args.forEachIndexed { i, arg -> fullArgs[offset + i] = arg }
        return onProceedListener.onProceed(fullArgs)
    }
}
